# Generated by Django 2.1.3 on 2018-11-19 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frontpage', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='temp',
            old_name='ill',
            new_name='origin',
        ),
        migrations.RenameField(
            model_name='temp',
            old_name='symptom',
            new_name='synonym',
        ),
    ]
