# Generated by Django 2.1.3 on 2018-11-19 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frontpage', '0002_auto_20181119_1942'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='temp',
            options={'managed': False},
        ),
    ]
